// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: libs/proto-files/post.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

//export const protobufPackage = "post";

export interface PostIdRequest {
  id: number;
}

export interface EmptyPostRequest {
}

export interface CreatePostRequest {
  id: number;
  title: string;
  content: string;
}

export interface UpdatePostRequest {
  id: number;
  title: string;
  content: string;
}

export interface Post {
  id: number;
  title: string;
  content: string;
}

export interface Posts {
  posts: Post[];
}

export const POST_PACKAGE_NAME = "post";

export interface PostServiceClient {
  getPostById(request: PostIdRequest): Observable<Post>;

  getAllPosts(request: EmptyPostRequest): Observable<Posts>;

  createPost(request: CreatePostRequest): Observable<Post>;

  updatePost(request: UpdatePostRequest): Observable<Post>;

  deletePost(request: PostIdRequest): Observable<Post>;
}

export interface PostServiceController {
  getPostById(request: PostIdRequest): Promise<Post> | Observable<Post> | Post;

  getAllPosts(request: EmptyPostRequest): Promise<Posts> | Observable<Posts> | Posts;

  createPost(request: CreatePostRequest): Promise<Post> | Observable<Post> | Post;

  updatePost(request: UpdatePostRequest): Promise<Post> | Observable<Post> | Post;

  deletePost(request: PostIdRequest): Promise<Post> | Observable<Post> | Post;
}

export function PostServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getPostById", "getAllPosts", "createPost", "updatePost", "deletePost"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PostService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const POST_SERVICE_NAME = "PostService";
